/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CodeRouteImport } from './routes/code'
import { Route as VerifierRouteImport } from './routes/verifier'
import { Route as AuthenticatedAccueilRouteImport } from './routes/_authenticated/accueil'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCaptureRouteImport } from './routes/_authenticated/capture'
import { Route as AuthenticatedCarnetRouteImport } from './routes/_authenticated/carnet'
import { Route as AuthenticatedClasserRouteImport } from './routes/_authenticated/classer'
import { Route as AuthenticatedFinancementRouteImport } from './routes/_authenticated/financement'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedPartageRouteImport } from './routes/_authenticated/partage'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as AuthenticatedRapportRouteImport } from './routes/_authenticated/rapport'
import { Route as AuthenticatedSaisieRouteImport } from './routes/_authenticated/saisie'
import { Route as AuthenticatedPartageOwnerIdRouteImport } from './routes/_authenticated/partage.$ownerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeRoute = CodeRouteImport.update({
  id: '/code',
  path: '/code',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifierRoute = VerifierRouteImport.update({
  id: '/verifier',
  path: '/verifier',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccueilRoute = AuthenticatedAccueilRouteImport.update({
  id: '/accueil',
  path: '/accueil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCaptureRoute = AuthenticatedCaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCarnetRoute = AuthenticatedCarnetRouteImport.update({
  id: '/carnet',
  path: '/carnet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClasserRoute = AuthenticatedClasserRouteImport.update({
  id: '/classer',
  path: '/classer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinancementRoute =
  AuthenticatedFinancementRouteImport.update({
    id: '/financement',
    path: '/financement',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPartageRoute = AuthenticatedPartageRouteImport.update({
  id: '/partage',
  path: '/partage',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRapportRoute = AuthenticatedRapportRouteImport.update({
  id: '/rapport',
  path: '/rapport',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSaisieRoute = AuthenticatedSaisieRouteImport.update({
  id: '/saisie',
  path: '/saisie',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPartageOwnerIdRoute =
  AuthenticatedPartageOwnerIdRouteImport.update({
    id: '/$ownerId',
    path: '/$ownerId',
    getParentRoute: () => AuthenticatedPartageRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/code': typeof CodeRoute
  '/verifier': typeof VerifierRoute
  '/accueil': typeof AuthenticatedAccueilRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/capture': typeof AuthenticatedCaptureRoute
  '/carnet': typeof AuthenticatedCarnetRoute
  '/classer': typeof AuthenticatedClasserRoute
  '/financement': typeof AuthenticatedFinancementRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/partage': typeof AuthenticatedPartageRouteWithChildren
  '/profil': typeof AuthenticatedProfilRoute
  '/rapport': typeof AuthenticatedRapportRoute
  '/saisie': typeof AuthenticatedSaisieRoute
  '/partage/$ownerId': typeof AuthenticatedPartageOwnerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/code': typeof CodeRoute
  '/verifier': typeof VerifierRoute
  '/accueil': typeof AuthenticatedAccueilRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/capture': typeof AuthenticatedCaptureRoute
  '/carnet': typeof AuthenticatedCarnetRoute
  '/classer': typeof AuthenticatedClasserRoute
  '/financement': typeof AuthenticatedFinancementRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/partage': typeof AuthenticatedPartageRouteWithChildren
  '/profil': typeof AuthenticatedProfilRoute
  '/rapport': typeof AuthenticatedRapportRoute
  '/saisie': typeof AuthenticatedSaisieRoute
  '/partage/$ownerId': typeof AuthenticatedPartageOwnerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/code': typeof CodeRoute
  '/verifier': typeof VerifierRoute
  '/_authenticated/accueil': typeof AuthenticatedAccueilRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/capture': typeof AuthenticatedCaptureRoute
  '/_authenticated/carnet': typeof AuthenticatedCarnetRoute
  '/_authenticated/classer': typeof AuthenticatedClasserRoute
  '/_authenticated/financement': typeof AuthenticatedFinancementRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/partage': typeof AuthenticatedPartageRouteWithChildren
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/_authenticated/rapport': typeof AuthenticatedRapportRoute
  '/_authenticated/saisie': typeof AuthenticatedSaisieRoute
  '/_authenticated/partage/$ownerId': typeof AuthenticatedPartageOwnerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/code'
    | '/verifier'
    | '/accueil'
    | '/admin'
    | '/capture'
    | '/carnet'
    | '/classer'
    | '/financement'
    | '/notifications'
    | '/partage'
    | '/profil'
    | '/rapport'
    | '/saisie'
    | '/partage/$ownerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/code'
    | '/verifier'
    | '/accueil'
    | '/admin'
    | '/capture'
    | '/carnet'
    | '/classer'
    | '/financement'
    | '/notifications'
    | '/partage'
    | '/profil'
    | '/rapport'
    | '/saisie'
    | '/partage/$ownerId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/code'
    | '/verifier'
    | '/_authenticated/accueil'
    | '/_authenticated/admin'
    | '/_authenticated/capture'
    | '/_authenticated/carnet'
    | '/_authenticated/classer'
    | '/_authenticated/financement'
    | '/_authenticated/notifications'
    | '/_authenticated/partage'
    | '/_authenticated/profil'
    | '/_authenticated/rapport'
    | '/_authenticated/saisie'
    | '/_authenticated/partage/$ownerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CodeRoute: typeof CodeRoute
  VerifierRoute: typeof VerifierRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code': {
      id: '/code'
      path: '/code'
      fullPath: '/code'
      preLoaderRoute: typeof CodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verifier': {
      id: '/verifier'
      path: '/verifier'
      fullPath: '/verifier'
      preLoaderRoute: typeof VerifierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/accueil': {
      id: '/_authenticated/accueil'
      path: '/accueil'
      fullPath: '/accueil'
      preLoaderRoute: typeof AuthenticatedAccueilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/capture': {
      id: '/_authenticated/capture'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof AuthenticatedCaptureRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/carnet': {
      id: '/_authenticated/carnet'
      path: '/carnet'
      fullPath: '/carnet'
      preLoaderRoute: typeof AuthenticatedCarnetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/classer': {
      id: '/_authenticated/classer'
      path: '/classer'
      fullPath: '/classer'
      preLoaderRoute: typeof AuthenticatedClasserRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financement': {
      id: '/_authenticated/financement'
      path: '/financement'
      fullPath: '/financement'
      preLoaderRoute: typeof AuthenticatedFinancementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/partage': {
      id: '/_authenticated/partage'
      path: '/partage'
      fullPath: '/partage'
      preLoaderRoute: typeof AuthenticatedPartageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rapport': {
      id: '/_authenticated/rapport'
      path: '/rapport'
      fullPath: '/rapport'
      preLoaderRoute: typeof AuthenticatedRapportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/saisie': {
      id: '/_authenticated/saisie'
      path: '/saisie'
      fullPath: '/saisie'
      preLoaderRoute: typeof AuthenticatedSaisieRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/partage/$ownerId': {
      id: '/_authenticated/partage/$ownerId'
      path: '/$ownerId'
      fullPath: '/partage/$ownerId'
      preLoaderRoute: typeof AuthenticatedPartageOwnerIdRouteImport
      parentRoute: typeof AuthenticatedPartageRoute
    }
  }
}

interface AuthenticatedPartageRouteChildren {
  AuthenticatedPartageOwnerIdRoute: typeof AuthenticatedPartageOwnerIdRoute
}

const AuthenticatedPartageRouteChildren: AuthenticatedPartageRouteChildren = {
  AuthenticatedPartageOwnerIdRoute: AuthenticatedPartageOwnerIdRoute,
}

const AuthenticatedPartageRouteWithChildren =
  AuthenticatedPartageRoute._addFileChildren(AuthenticatedPartageRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccueilRoute: typeof AuthenticatedAccueilRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCaptureRoute: typeof AuthenticatedCaptureRoute
  AuthenticatedCarnetRoute: typeof AuthenticatedCarnetRoute
  AuthenticatedClasserRoute: typeof AuthenticatedClasserRoute
  AuthenticatedFinancementRoute: typeof AuthenticatedFinancementRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedPartageRoute: typeof AuthenticatedPartageRouteWithChildren
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedRapportRoute: typeof AuthenticatedRapportRoute
  AuthenticatedSaisieRoute: typeof AuthenticatedSaisieRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccueilRoute: AuthenticatedAccueilRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCaptureRoute: AuthenticatedCaptureRoute,
  AuthenticatedCarnetRoute: AuthenticatedCarnetRoute,
  AuthenticatedClasserRoute: AuthenticatedClasserRoute,
  AuthenticatedFinancementRoute: AuthenticatedFinancementRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedPartageRoute: AuthenticatedPartageRouteWithChildren,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
  AuthenticatedRapportRoute: AuthenticatedRapportRoute,
  AuthenticatedSaisieRoute: AuthenticatedSaisieRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CodeRoute: CodeRoute,
  VerifierRoute: VerifierRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
